# Generated by Django 4.0.5 on 2022-07-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_periods',
            name='task_id',
        ),
        migrations.DeleteModel(
            name='tasks',
        ),
        migrations.DeleteModel(
            name='work_periods',
        ),
    ]
