# Generated by Django 4.0.5 on 2022-07-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptime', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='assigned_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='label',
            field=models.IntegerField(default='None'),
        ),
    ]
