# Generated by Django 4.0.5 on 2022-07-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptime', '0004_alter_tasks_assigned_date_alter_tasks_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='label',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
