# Generated by Django 4.0.5 on 2022-07-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptime', '0005_alter_tasks_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_periods',
            name='finish_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='work_periods',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='work_periods',
            name='total_time',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
