# Generated by Django 4.0.5 on 2022-08-03 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apptime', '0006_alter_work_periods_finish_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='assigned_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
