# Generated by Django 4.0.8 on 2022-12-08 21:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('apptime', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=tinymce.models.HTMLField(default='None'),
        ),
    ]
