# Generated by Django 4.0.8 on 2022-12-23 02:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('apptime', '0009_alter_tasks_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='month_note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', tinymce.models.HTMLField(default='None')),
            ],
        ),
    ]
