# Generated by Django 4.0.8 on 2022-12-23 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptime', '0010_month_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='month_note',
        ),
    ]
