# Generated by Django 4.0.8 on 2022-12-23 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptime', '0012_month_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month_note',
            old_name='description',
            new_name='notes',
        ),
    ]
